node_movement:
  ros__parameters:
    COXA_LENGTH: 0.050
    FEMUR_LENGTH: 0.063
    TIBIA_LENGTH: 0.099
    COXA_HEIGHT: 0.045

################################
# Coordinate system body

#    ▲ x
#    │
#    │
#   (x)─────▶ y
#      z

    LEG_NAMES: ['RightFront', 'RightMid', 'RightBack', 'LeftFront', 'LeftMid', 'LeftBack']
    CENTER_TO_COXA_X:      [0.109,   0.0, -0.109,  0.109,    0.0, -0.109]
    CENTER_TO_COXA_Y:      [0.068, 0.088,  0.068, -0.068, -0.088, -0.068]
    OFFSET_COXA_ANGLE_DEG: [45.0,   90.0,  135.0, -45.0,   -90.0, -135.0] 


    BODY_MAX_ROLL: 15.0  # deg
    BODY_MAX_PITCH: 15.0 # deg
    BODY_MAX_YAW: 20.0   # deg

    HEAD_MAX_YAW: 30.0
    HEAD_MAX_PITCH: 20.0

    #### GENERIC GAIT PARAMETERS ####
    LEG_LIFT_HEIGHT: 0.025      # [m]   // -0.05 + 0.025 = -0.025
    GAIT_STEP_LENGTH: 0.03     # [m]
    FACTOR_VELOCITY_TO_GAIT_CYCLE_TIME: 40.0      # [s²/m] ??

    #### TRIPOD GAIT PARAMETERS ####
    HEAD_MAX_YAW_TRIPOD: 15.0 # deg

    #### LEG WAVE GAIT PARAMETERS ####
    GAIT_LEG_WAVE_LEG_LIFT_HEIGHT: 0.03 # m

