node_movement:
  ros__parameters:
    SERIAL_PORT: '/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0'   # "/dev/ttyUSB0"

    SERVO_NAME: ['HEAD_YAW', 'HEAD_PITCH',
                 'LEG_RIGHT_FRONT_COXA', 'LEG_RIGHT_FRONT_FEMUR', 'LEG_RIGHT_FRONT_TIBIA',
                 'LEG_RIGHT_MID_COXA', 'LEG_RIGHT_MID_FEMUR', 'LEG_RIGHT_MID_TIBIA',
                 'LEG_RIGHT_BACK_COXA', 'LEG_RIGHT_BACK_FEMUR', 'LEG_RIGHT_BACK_TIBIA',
                 'LEG_LEFT_FRONT_COXA', 'LEG_LEFT_FRONT_FEMUR', 'LEG_LEFT_FRONT_TIBIA',
                 'LEG_LEFT_MID_COXA', 'LEG_LEFT_MID_FEMUR', 'LEG_LEFT_MID_TIBIA',
                 'LEG_LEFT_BACK_COXA', 'LEG_LEFT_BACK_FEMUR', 'LEG_LEFT_BACK_TIBIA'] 

    SERVO_ADAPTATION_DEG: [  5.0, -14.0,          # HEAD: YAW, PITCH
                             0.0,   0.0,   0.0,   # LEG_RIGHT_FRONT: COXA, FEMUR, TIBIA
                             0.0,   0.0,   0.0,   # LEG_RIGHT_MID:   COXA, FEMUR, TIBIA
                           +10.0,   0.0,   0.0,   # LEG_RIGHT_BACK:  COXA, FEMUR, TIBIA
                             0.0,   0.0,   0.0,   # LEG_LEFT_FRONT:  COXA, FEMUR, TIBIA
                             0.0,   0.0,   0.0,   # LEG_LEFT_MID:    COXA, FEMUR, TIBIA 
                             0.0,   0.0,   0.0]   # LEG_LEFT_BACK:   COXA, FEMUR, TIBIA

    SERVO_OFFSET_DEG: [0.0, 0.0,         # HEAD: YAW, PITCH
                       0.0, 20.0, -3.0,  # LEG_RIGHT_FRONT: COXA, FEMUR, TIBIA
                       0.0, 20.0, -3.0,  # LEG_RIGHT_MID:   COXA, FEMUR, TIBIA
                       0.0, 20.0, -3.0,  # LEG_RIGHT_BACK:  COXA, FEMUR, TIBIA
                       0.0, 20.0, -3.0,  # LEG_LEFT_FRONT:  COXA, FEMUR, TIBIA
                       0.0, 20.0, -3.0,  # LEG_LEFT_MID:    COXA, FEMUR, TIBIA 
                       0.0, 20.0, -3.0]  # LEG_LEFT_BACK:   COXA, FEMUR, TIBIA

    SERVO_ORIENTATION_CLOCKWISE: [True, True,         # HEAD: YAW, PITCH
                                  True, True, True,  # LEG_RIGHT_FRONT: COXA, FEMUR, TIBIA
                                  True, True, True,  # LEG_RIGHT_MID:   COXA, FEMUR, TIBIA
                                  True, True, True,  # LEG_RIGHT_BACK:  COXA, FEMUR, TIBIA
                                  True, False, False, # LEG_LEFT_FRONT:  COXA, FEMUR, TIBIA
                                  True, False, False, # LEG_LEFT_MID:    COXA, FEMUR, TIBIA 
                                  True, False, False] # LEG_LEFT_BACK:   COXA, FEMUR, TIBIA

# Servo Serial ID Layout
#
#            020
#            010
#             |
# 036-026-016-|-011-021-031
#             |
# 035-025-015-|-012-022-032
#             |
# 034-024-014-|-013-023-033
#
    SERVO_SERIAL_ID: [10, 20,      # HEAD: YAW, PITCH
                      11, 21, 31,  # LEG_RIGHT_FRONT: COXA, FEMUR, TIBIA
                      12, 22, 32,  # LEG_RIGHT_MID:   COXA, FEMUR, TIBIA
                      13, 23, 33,  # LEG_RIGHT_BACK:  COXA, FEMUR, TIBIA
                      16, 26, 36,  # LEG_LEFT_FRONT:  COXA, FEMUR, TIBIA  
                      15, 25, 35,  # LEG_LEFT_MID:    COXA, FEMUR, TIBIA 
                      14, 24, 34]  # LEG_LEFT_BACK:   COXA, FEMUR, TIBIA
